// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4LyBG6FxqxUX12OvBXAzUQI-mK6Vt5M',
    appId: '1:710221840901:web:499df0623a21473f0e926c',
    messagingSenderId: '710221840901',
    projectId: 'sitforsa',
    authDomain: 'sitforsa.firebaseapp.com',
    storageBucket: 'sitforsa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGazwe1dyU8um4CTnNIgl8Q4jBdiV4DE',
    appId: '1:710221840901:android:ae5ac38dffeadd460e926c',
    messagingSenderId: '710221840901',
    projectId: 'sitforsa',
    storageBucket: 'sitforsa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfSvVfRIKif-FT2k4QcZ7evDM60aTAwY',
    appId: '1:710221840901:ios:8796adb90b895bbc0e926c',
    messagingSenderId: '710221840901',
    projectId: 'sitforsa',
    storageBucket: 'sitforsa.appspot.com',
    androidClientId: '710221840901-fpbn4mli8qjsb21rc0iepnjhuj14antv.apps.googleusercontent.com',
    iosClientId: '710221840901-1fqrob8iots9jatrjttbkgmk230m6bnc.apps.googleusercontent.com',
    iosBundleId: 'com.project.sitforsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfSvVfRIKif-FT2k4QcZ7evDM60aTAwY',
    appId: '1:710221840901:ios:8796adb90b895bbc0e926c',
    messagingSenderId: '710221840901',
    projectId: 'sitforsa',
    storageBucket: 'sitforsa.appspot.com',
    androidClientId: '710221840901-fpbn4mli8qjsb21rc0iepnjhuj14antv.apps.googleusercontent.com',
    iosClientId: '710221840901-1fqrob8iots9jatrjttbkgmk230m6bnc.apps.googleusercontent.com',
    iosBundleId: 'com.project.sitforsa',
  );
}
